# .github/workflows/job-scraper.yml
name: Daily Job Scraper

on:
  schedule:
    # Run every day at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Allow pushing changes back to repo
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run diagnostics
      run: python diagnose.py  
      
    - name: Run job scraper
      run: python job_scraper.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || git commit -m "🔍 Daily job scraper update - $(date '+%Y-%m-%d %H:%M')"
        git push || echo "No changes to push"
        
    - name: Deploy to GitHub Pages (optional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        publish_branch: gh-pages
